export enum Routes {
  Intro = 'Intro',
  Auth = 'Auth',
  Register = 'Register',
  Tutorial = 'Tutorial',
  SearchPage = 'SearchPage',
  SearchResult = 'SearchResult',
  Vacancy = 'Vacancy',
  VacancyList = 'VacancyList',
  Company = 'Company',
  Favorites = 'Favorites',
  Feedback = 'Feedback',
  Profile = 'Profile',
  ProfileEdit = 'ProfileEdit',
  Chat = 'Chat',
  Settings = 'Settings',
  Resume = 'Resume',
  ResumeEdit = 'ResumeEdit',
  ResumeCreate = 'ResumeCreate',
  ResumeTutorial = 'ResumeTutorial',
  VideoScreen = 'VideoScreen',
  CameraScreen = 'CameraScreen',
  Premium = 'Premium',
  Error = 'Error',
  EditVideoScreen = 'EditVideoScreen',
}

export const RouteActive: Routes = Routes.ProfileEdit;
