export enum Icons {
  back = require('../assets/img/icons/back.png'),
  archive = require('../assets/img/icons/archive.png'),
  apple = require('../assets/img/icons/apple.png'),
  google = require('../assets/img/icons/google.png'),
  facebook = require('../assets/img/icons/facebook.png'),
  vk = require('../assets/img/icons/vk.png'),
  ok = require('../assets/img/icons/ok.png'),
  filter = require('../assets/img/icons/filter.png'),
  flag = require('../assets/img/icons/flag.png'),
  heartActive = require('../assets/img/icons/heartActive.png'),
  heartActiveOutline = require('../assets/img/icons/heartActive.png'),
  heart = require('../assets/img/icons/heart.png'),
  feedback = require('../assets/img/icons/feedback.png'),
  feedbackActive = require('../assets/img/icons/feedbackActive.png'),
  chat = require('../assets/img/icons/chat.png'),
  chatActive = require('../assets/img/icons/chatActive.png'),
  basket = require('../assets/img/icons/basket.png'),
  cameraShoot = require('../assets/img/icons/cameraShoot.png'),
  play = require('../assets/img/icons/play.png'),
  profile = require('../assets/img/icons/profile.png'),
  profileActive = require('../assets/img/icons/profileActive.png'),
  search = require('../assets/img/icons/search.png'),
  searchActiveOutline = require('../assets/img/icons/searchActiveOutline.png'),
  send = require('../assets/img/icons/send.png'),
}
